backend:
  name: github
  repo: netlify/netlify-cms
  branch: roadmap
  squash_merges: true

# publish_mode: editorial_workflow

media_folder: "website/static/img" # Folder where user uploaded files should go
public_folder: "img"

collections: # A list of collections the CMS should be able to edit
  - name: pages
    label: Pages
    files:
      - name: community
        label: Community
        file: website/content/pages/community.md
        fields:
          - { name: title, label: Title }
          - { name: headline, label: Headline }
          - { name: subhead, label: Subheading, widget: markdown }
          - { name: primarycta, label: Call To Action, widget: markdown }
          - { name: upcomingevent, label: Event, widget: object, fields: [
              { name: hook, label: Intro, widget: text }
            ]}
          - { name: howitworks, label: How It Works, widget: text }
          - { name: howtojoin, label: How To Join, widget: markdown }
      - name: roadmap
        label: Roadmap
        file: website/content/pages/roadmap.md
        fields:
          - { name: title, label: Title }
          - { name: description, label: Description, widget: text }
          - { name: heading, label: Heading }
          - { name: intro, label: Intro, widget: text }
          - { name: body, label: Roadmap, widget: markdown }

  - name: "docs" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Docs" # Used in the UI, ie.: "New Post"
    folder: "website/content/docs" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Group", name: "group", widget: "string"}
      - {label: "Weight", name: "weight", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "blog"
    label: "Blog"
    label_singular: "Post"
    folder: "website/content/blog"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Description (for blog list)", name: "description", widget: "text"}
      - {label: "Meta Description (defaults to Description)", name: "meta_description", widget: "text", required: false}
      - {label: "Twitter Image", name: "twitter_image", widget: "image"}
      - {label: "Date", name: "date", widget: "date"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: updates
    label: Updates
    files:
      - name: releases
        label: Releases
        file: website/data/updates.yml
        fields:
          - name: updates
            label: Releases
            widget: list
            fields:
              - {name: version, label: Version}
              - {name: date, label: Date, widget: date}
              - {name: description, label: Description}
      - name: notifications
        label: Notifications
        file: website/data/notifications.yml
        description: Site-top notifications - publish one at a time
        fields:
          - name: notifications
            label: Notifications
            widget: list
            fields:
              - {label: Title, name: title, widget: string, tagname: h1}
              - {label: Published, name: published, widget: boolean}
              - {label: Loud, name: loud, widget: boolean}
              - {label: Message, name: message, widget: text}
              - {label: URL, name: url}
